templateDir: templates
additionalProperties:
    packageName: braze_ex
    invokerPackage: BrazeEx
    disallowAdditionalPropertiesIfNotPresent: false
    licenseId: MIT
    mixLinks: '%{github: "https://github.com/gerbal/braze_ex"}'
    legacyDiscriminatorBehavior: false
    enumUnknownDefaultCase: true
    customDeps: 
        - '{:tesla, "~> 1.4"}'
        - '{:jason, "> 0.0.0"}'
        - '{:ex_doc, "~> 0.28", only: :dev, runtime: false}'

