name: Main workflow

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: 0 0 * * *

jobs:
  update_specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Git
        run: |
          git config --global user.name "Continuous Deployment"
          git config --global user.email 'github@users.noreply.github.com'

      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1
      - uses: extractions/setup-just@v1
      - run: just build
      - name: check for changes
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with: 
          files: |
            priv
      - run: just bump-version
        if: steps.verify-changed-files.outputs.files_changed == 'true'
      - run: just publish
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}